Antra.CRMApp.WebMVC/Controllers/ShipperController.cs
using Antra.CRMApp.Core.Contract.Service;
using Antra.CRMApp.Core.Model;
using Microsoft.AspNetCore.Mvc;

namespace Antra.CRMApp.WebMVC.Controllers
{
    public class ShipperController : Controller
    {
        private readonly IShipperServiceAsync shipperServiceAsync;
        public ShipperController(IShipperServiceAsync ship)
        {
            shipperServiceAsync = ship;
        }

        public async Task<IActionResult> Index()
        {
            var result = await shipperServiceAsync.GetAllAsync();
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ShipperModel model)
        {
            if (ModelState.IsValid)
            {
                await shipperServiceAsync.AddShipperAsync(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.IsEdit = false;
            var shipModel = await shipperServiceAsync.GetShipperForEditAsync(id);
            return View(shipModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ShipperModel model)
        {
            ViewBag.IsEdit = false;
            if (ModelState.IsValid)
            {
                await shipperServiceAsync.UpdateShipperAsync(model);
                ViewBag.IsEdit = true;
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await shipperServiceAsync.DeleteShipperAsync(id);
            return RedirectToAction("Index");
        }
    }
}

Antra.CRMApp.WebMVC/Views/Shipper/Create.cshtml
@model ShipperModel
<form asp-action="Create" asp-controller="Shipper" method="post">
    <h1 class="display-6">Add New Shipper</h1>
    <hr/>
    <div class="container">
        <div class="row">
            <div class="col mb-5">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name"></span>
            </div>
        </div>
         <div class="row">
            <div class="col mb-5">
                <label asp-for="Phone"></label>
                <input asp-for="Phone" class="form-control"/>
                <span asp-validation-for="Phone"></span>
            </div>
        </div>
        <input type="submit" class="btn-primary btn" value="Create Shipper"/>
    </div>
</form>

Antra.CRMApp.WebMVC/Views/Shipper/Edit.cshtml
@model ShipperModel

@if (ViewBag.IsEdit==true)
{
    
    
        <div class="container">
            <di class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Shipper Updated Successfully. Go to <a asp-action="Index" asp-controller="Shipper" >Index</a> </strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
}

<form asp-action="Edit" asp-controller="Shipper" method="post">
    <h1 class="display-6">Edit Shipper</h1>
    <hr/>
    <div class="container">
        <div class="row">
            <div class="col mb-5">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name"></span>
            </div>
        </div>
         <div class="row">
            <div class="col mb-5">
                <label asp-for="Phone"></label>
                <input asp-for="Phone" class="form-control"/>
                <span asp-validation-for="Phone"></span>
            </div>
        </div>
        <input type="submit" class="btn-primary btn" value="Edit Shipper"/>
    </div>
</form>

Antra.CRMApp.WebMVC/Views/Shipper/Index.cshtml
@model IEnumerable<ShipperModel>
<a asp-action="Create" asp-controller="Shipper" class="btn bg-success" >Add Shipper</a>
<table class="table table-striped">
  <thead>
      <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Phone</th>
      </tr>
  </thead>
  <tbody>
      @foreach(var m in Model)
        {
            <tr>
                <td>@m.Id</td>
                <td>@m.Name</td>
                <td>@m.Phone</td>
                <td><a asp-action="Edit" asp-controller="Shipper" asp-route-id="@m.Id" class="btn btn-primary">Edit</a></td>
                <td><a class="btn bg-danger" asp-action="Delete" asp-controller="Shipper" asp-route-id="@m.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>